### ISSUE TITLE
Dedicated deployment for bedrock integration tests

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1185]
From discussion in https://github.com/mozilla/bedrock/pull/8286
- [X] cert: arn:aws:acm:us-west-2:236517346949:certificate/1f05b4cd-09ff-423b-8443-2567eab6c7e4
- [x] ELB: https://github.com/mozmeao/infra/pull/1186
  - bedrock-test-1512358064.us-west-2.elb.amazonaws.com
- [x] DNS: bedrock-test.moz.works CNAME bedrock-test-1512358064.us-west-2.elb.amazonaws.com
- [x] bedrock-test namespace: mozmeao/www-config#255
- [x] nodeport service: mozmeao/www-config#255
- [x] secrets: https://github.com/mozmeao/infra-private/commit/e1dcb56c63c119047deeca5311a6ca16f49f12b1
- [x] configmap: mozmeao/www-config#255
- [x] deployment: mozmeao/www-config#255
- [x] https://bedrock-test.moz.works is live
- [x] deploy and test on push to run-integration-tests branch of bedrock mozilla/bedrock#8288
